- name: Ansible Copy WAR File Local to Remote
  hosts: all
  become: true
  tasks:
    - name: copying file with playbook
      become: true
      copy:
        src: /home/ubuntu/hello-world-1.war
        dest: /opt/tomcat/webapps/
